### PR TITLE
F1

### PR DESCRIPTION
**Pull request by itsz3us**
Hey, This removes hard-coded placeholder in the input fields, make them more dynamic. Additionally, two tabs added, Inbox and Sent. Just to make it be more realistic.  

alt text

### CODE REVIEW

**Comment by code-zm** [comment]
I like the overall feel of this GUI however I don't like having to switch back and forth between the sent and inbox tabs.

The goal of this is to have a similar UI to other messaging platforms. Here is an example in customTKInter:
messageAppExample

This won't work yet as there is no username system, but that should give you a better idea of what to build.

I appreciate your contribution!

**Comment by code-zm** [comment]
Thanks for the heads up about the input fields!
While I appreciate your contribution to the tkInter GUI, I decided to change the entire front end to Kivy.
I will push to github soon.
Thanks!

**Comment by itsz3us** [comment]
Are you on Nym telegram channel ?

**Comment by code-zm** [comment]
I will join, I just made an account

**Pull request closed without merging**
